# Example BitBucket pipeline for a mysql database.
image: spacebabies/ci-2.4.1
pipelines:
  default:
    - step: &run_tests
        script:
          - export DATABASE_URL=postgresql://test_user:test_user_password@localhost/pipelines
        services:
          - postgres
definitions:
  services:
    postgres:
      image: postgres
      environment:
        POSTGRES_DB: pipelines
        POSTGRES_USER: test_user
        POSTGRES_PASSWORD: test_user_password
