image: spacebabies/ci-2.4.1

pipelines:
  default:
    - step: &run_tests
        name: Run the tests
        caches:
          - bundler
          - sprockets
        script:
          - sentry-cli releases new ${BITBUCKET_COMMIT}
          - export DATABASE_URL=postgresql://test_user:test_user_password@localhost/pipelines
          - bundle install --deployment --jobs 4
          - bundle exec rake db:schema:load
          - bundle exec rake
        services:
          - postgres
          - redis
    - step: &finalize_release
        name: Finalize release
        script:
          - sentry-cli releases set-commits --commit "${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}@${BITBUCKET_COMMIT}" ${BITBUCKET_COMMIT}
          - sentry-cli releases finalize ${BITBUCKET_COMMIT}

  branches:
    master:
      - step:
          <<: *run_tests
      - step:
          <<: *finalize_release
      - step:
          name: Deploy to production
          deployment: production
          script:
            - sentry-cli releases deploys ${BITBUCKET_COMMIT} new -e production
            - curl -X POST $REDEPLOYMENT_HOOK
    staging:
      - step:
          <<: *run_tests
      - step:
          <<: *finalize_release
      - step:
          name: Deploy to staging
          deployment: staging
          script:
            - sentry-cli releases deploys ${BITBUCKET_COMMIT} new -e staging
            - curl -X POST $STAGING_REDEPLOYMENT_HOOK

definitions:
  caches:
    bundler: vendor/bundle
    sprockets: tmp/cache
  services:
    postgres:
      image: postgres
      environment:
        POSTGRES_DB: pipelines
        POSTGRES_USER: test_user
        POSTGRES_PASSWORD: test_user_password
    redis:
      image: redis:4
