# Example BitBucket pipeline for a mysql database.
image: spacebabies/ci-2.4.1
shared_steps:
  - run_tests: &run_tests
        name: Run the tests
        script:
          - export DATABASE_URL=mysql2://test_user:test_user_password@localhost/pipelines
        services:
          - mysql
pipelines:
  default:
    - step: *run_tests
definitions:
  services:
    mysql:
      image: mysql:5.7
      environment:
        MYSQL_DATABASE: 'pipelines'
        MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
        MYSQL_USER: 'test_user'
        MYSQL_PASSWORD: 'test_user_password'
